Update 2024.md
mautic/low-no-code pull request #108
Opened 2024-12-17 17:33 UTC by Danbaba1

## Description
This pull request updates the 2024.md file to include a new contribution and link to the associated issue.

## Changes
- Edited the 2024.md file
- Added a new entry at the bottom of the list with:
  - Contribution details
  - Link to the related issue

## Checklist
- [x] Updated the correct file for the current year
- [x] Added contribution information
- [x] Included issue link

## Related Issue
Relates to [#21]

2024-12-17 17:57 UTC, RCheesley requested changes
Just a small change, to add it to the bottom section, ongoing contributions :)

2024-12-17 17:57 UTC, RCheesley commented on 2024.md
> +| Daniel Oladepo (@Danbaba1)      | [#21](https://github.com/mautic/low-no-code/issues/21)           | Reviewed and updated the Requirements page                             |
Please move this to the 'ongoing contributions' section below, as Hacktoberfest is now over - so we have another section to use :)

2024-12-17 19:01 UTC, Danbaba1 commented
Yes will do that

On Tue, Dec 17, 2024 at 6:57 PM Ruth Cheesley ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Just a small change, to add it to the bottom section, ongoing
> contributions :)
> ------------------------------
>
> In 2024.md
> <https://github.com/mautic/low-no-code/pull/108#discussion_r1888976061>:
>
> > @@ -173,6 +173,7 @@ When linking to your contribution, please write a descriptive title and use the
>  | Rahul Shinde (shinde-rahul)         | [#14191](https://github.com/mautic/mautic/pull/14191)            | User testing                                                             |
>  | Markus Heinilä (markusvjh)          | [#64](https://github.com/mautic/hacktoberfest-no-code/issues/64) | New Blogpost, formatting and aligning with CSS                           |
>  | Efe Akhigbe ***@***.***)           | [#43](https://github.com/mautic/low-no-code/issues/43)           | Created visual asssets for the Mautic 5.2.0 release                      |
> +| Daniel Oladepo ***@***.***)      | [#21](https://github.com/mautic/low-no-code/issues/21)           | Reviewed and updated the Requirements page                             |
>
> Please move this to the 'ongoing contributions' section below, as
> Hacktoberfest is now over - so we have another section to use :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mautic/low-no-code/pull/108#pullrequestreview-2509664903>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXRP57XDESSKNZPLUDTC2EL2GBQZHAVCNFSM6AAAAABTY5XFROVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBZGY3DIOJQGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-17 19:09 UTC, Danbaba1 commented on 2024.md
> +| Daniel Oladepo (@Danbaba1)      | [#21](https://github.com/mautic/low-no-code/issues/21)           | Reviewed and updated the Requirements page                             |
Okay noted

2024-12-17 19:19 UTC, Danbaba1 commented on 2024.md
> +| Daniel Oladepo (@Danbaba1)      | [#21](https://github.com/mautic/low-no-code/issues/21)           | Reviewed and updated the Requirements page                             |
@RCheesley I have made the change

2025-01-14 09:31 UTC, RCheesley approved these changes
Thanks @Danbaba1 sorry for the delay!

2025-01-14 09:32 UTC, merged